[package]
name = "seer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive"] }
env_logger = "0.11.8"
hex = "0.4.3"
log = "0.4.27"
nix = { version = "0.29.0", features = ["ptrace"] }
