[workspace]
resolver = "2"
members = ["seer", "linux", "windows"]

[workspace.dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.27"
nix = { version = "0.29.0", features = ["ptrace"] }
